"""Negative controls for audit provenance; no private binary is required."""
import importlib.util
from pathlib import Path
import tempfile
import unittest


def load(name):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).parents[1] / "tools" / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


verify = load("Verify-Fable2XexProvenance")
inventory = load("Fable2ComparativeInventory")


class ProvenanceNegativeControls(unittest.TestCase):
    def test_different_instruction_fails_generated_comparison(self):
        with tempfile.TemporaryDirectory() as root:
            first, second = Path(root) / "a", Path(root) / "b"
            first.mkdir()
            second.mkdir()
            (first / "f.cpp").write_text("r11 = 2;\n")
            (second / "f.cpp").write_text("r11 = 1;\n")
            with self.assertRaisesRegex(ValueError, "generated bytes differ"):
                verify.generated_comparison(first, second)

    def test_missing_translation_unit_fails(self):
        with tempfile.TemporaryDirectory() as root:
            first, second = Path(root) / "a", Path(root) / "b"
            first.mkdir()
            second.mkdir()
            (first / "f.cpp").write_text("unchanged\n")
            with self.assertRaisesRegex(ValueError, "census"):
                verify.generated_comparison(first, second)

    def test_wrong_image_rejected_before_parsing(self):
        with tempfile.TemporaryDirectory() as root:
            directory = Path(root)
            (directory / "image.bin").write_bytes(b"wrong revision")
            with self.assertRaisesRegex(ValueError, "wrong image identity"):
                inventory.load_image(directory, inventory.TU1_IMAGE)

    def test_branch_mask_does_not_authorize_ambiguous_identity(self):
        # Two branch destinations can collapse. The index must retain both.
        first, second = bytes.fromhex("48000005"), bytes.fromhex("48000105")
        index = inventory.match_index({0x1000: first, 0x2000: second}, True)
        self.assertEqual(index[inventory.branch_key(first)], [0x1000, 0x2000])
        self.assertNotEqual(inventory.branch_key(bytes.fromhex("39600001")),
                            inventory.branch_key(bytes.fromhex("39600002")))


if __name__ == "__main__":
    unittest.main()
