#!/usr/bin/env python3
"""Read-only check of load-only snapshots and an isolated full regeneration.

Run the probe and regeneration described in tools/xex-provenance/README.md first.
This validates image/generation provenance, not the correctness of PPC translation.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def sha(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def snapshot(directory: Path, mode: str, expected: dict) -> dict:
    with (directory / "identity.tsv").open() as stream:
        identities = list(csv.DictReader(stream, delimiter="\t"))
    require(len(identities) == 1, "snapshot must have one identity")
    identity = identities[0]
    require(identity["mode"] == mode, f"wrong snapshot mode: {directory}")
    require(int(identity["base"]) == int(expected["image_base"], 16), "image base mismatch")
    require(int(identity["size"]) == int(expected["image_size"], 16), "image size mismatch")
    image = directory / "image.bin"
    require(image.stat().st_size == int(identity["size"]), "truncated/oversized image")
    digest = sha(image)
    require(digest == expected["patched_image_sha256"], f"patched image mismatch: {directory}")
    with (directory / "sections.tsv").open() as stream:
        sections = list(csv.DictReader(stream, delimiter="\t"))
    executable = [s for s in sections if s["executable"] == "1"]
    wanted = expected["executable_sections"]
    require(len(executable) == len(wanted), "executable section count mismatch")
    data = image.read_bytes()
    for actual, target in zip(executable, wanted):
        require(actual["name"] == target["name"], "section name mismatch")
        start, size = int(actual["address"]), int(actual["size"])
        require(start == int(target["start"], 16) and size == int(target["size"], 16),
                "section extent mismatch")
        offset = start - int(identity["base"])
        require(hashlib.sha256(data[offset:offset + size]).hexdigest().upper() == target["sha256"],
                "section hash mismatch")
    module_path = Path((directory / "runtime-module.txt").read_text().strip())
    return {"directory": str(directory.resolve()), "mode": mode,
            "image_sha256": digest, "identity": identity, "sections": sections,
            "loaded_runtime_path": str(module_path), "runtime_sha256": sha(module_path),
            "layout": (directory / "layout.tsv").read_text().splitlines()}


def generated_comparison(current: Path, regenerated: Path) -> dict:
    def names(directory: Path) -> set[str]:
        return {p.name for p in directory.iterdir() if p.suffix in {".cpp", ".h"}}
    existing, fresh = names(current), names(regenerated)
    require(bool(existing) and existing == fresh, "generated file census differs or is empty")
    records = []
    for name in sorted(existing):
        first, second = sha(current / name), sha(regenerated / name)
        require(first == second, f"generated bytes differ: {name}")
        records.append({"file": name, "sha256": first})
    inventory = json.dumps(records, sort_keys=True, separators=(",", ":")).encode()
    return {"status": "PASS", "identical_files": len(records),
            "inventory_sha256": hashlib.sha256(inventory).hexdigest().upper(),
            "current": str(current.resolve()), "regenerated": str(regenerated.resolve())}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tool-snapshot", type=Path, required=True)
    parser.add_argument("--runtime-snapshot", type=Path, required=True)
    parser.add_argument("--regenerated", type=Path, required=True)
    parser.add_argument("--generated", type=Path, default=ROOT / "generated/default")
    parser.add_argument("--runtime-directory", type=Path, default=ROOT / "out/build/win-amd64-release")
    parser.add_argument("--evidence", type=Path, default=ROOT / "tools/fable2-entrypoint-closure-evidence.json")
    args = parser.parse_args()
    try:
        expected = json.loads(args.evidence.read_text())["expected_image_identity"]
        tool = snapshot(args.tool_snapshot, "tool", expected)
        runtime = snapshot(args.runtime_snapshot, "runtime", expected)
        require(tool["identity"]["entry"] == runtime["identity"]["entry"], "entry point mismatch")
        require(tool["sections"] == runtime["sections"], "section layout mismatch")
        require(tool["layout"] == runtime["layout"], "loader header layout mismatch")
        staged_runtime = args.runtime_directory / "rexruntime.dll"
        require(tool["runtime_sha256"] == runtime["runtime_sha256"] == sha(staged_runtime),
                "probe and normal staged runtime DLLs differ")
        inputs = []
        for directory in (ROOT / "assets/tu1", ROOT / "assets/runtime"):
            for name, key in (("default.xex", "base_xex_sha256"),
                              ("default.xexp", "title_update_sha256")):
                path = directory / name
                digest = sha(path)
                require(digest == expected[key], f"source identity mismatch: {path}")
                inputs.append({"path": str(path), "sha256": digest, "size": path.stat().st_size})
        cache = (ROOT / "out/build/win-amd64-release/CMakeCache.txt").read_text()
        package = next(line.split("=", 1)[1] for line in cache.splitlines()
                       if line.startswith("rexglue_DIR:"))
        sdk = (Path(package) / "../../..").resolve()
        require(sha(sdk / "bin/rexruntime.dll") == tool["runtime_sha256"],
                "installed codegen runtime DLL differs")
        generated = generated_comparison(args.generated, args.regenerated)
        print(json.dumps({"schema_version": 1, "status": "VERIFIED CONSISTENT",
                          "scope": "fresh load-only snapshots and generated source; no guest execution or translation-correctness proof",
                          "source_inputs": inputs, "tool": tool, "runtime": runtime,
                          "generated": generated,
                          "installed_cli": {"path": str(sdk / "bin/rexglue.exe"),
                                            "sha256": sha(sdk / "bin/rexglue.exe")},
                          "evidence_sha256": sha(args.evidence)}, indent=2))
        return 0
    except (OSError, ValueError, KeyError, StopIteration) as error:
        print(f"FAIL: {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
